name: pertaminapay
description: Aplikasi Pembayaran BBM Pertamina - PertaminaPay.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1  # Untuk font Poppins di UI

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Untuk linting code

flutter:
  uses-material-design: true

  # Assets (kalau nanti tambah gambar/icon, uncomment dan tambah di sini)
  # assets:
  #   - images/
  #   - icons/

  # Fonts (kalau mau custom font selain Google Fonts, tambah di sini)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic